avoid leaking internal s3client struct name to the outside, favor s3-endpoint
Mostly affects docs and some JS UI components, but also changes the
section type name of the s3 client endpoints.

While the s3 client crate is aptly named, the config actually
describing how to access an S3 object storage is not really a client,
but a definition of an endpoint/remote/repo/address.

This is really no problem per se, but such internal names tend to leak
and can cause (a tiny bit!) confusion for users if they see with e.g.
"S3 Endpoints" in the UI but the same thing now uses "s3client" in the
config file.

Signed-off-by: Thomas Lamprecht <t.lamprecht@proxmox.com>

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -39,6 +39,14 @@ case "$1" in
 			    || echo "Failed to move prune jobs, please check manually"
 		fi
 
+		# TODO: remove with 4.1+, this was just exposed on internal testing.
+		if dpkg --compare-versions "$2" 'lt' '4.0.5~'; then
+			if [ -e /etc/proxmox-backup/s3.cfg ]; then
+				sed -i 's/^s3client:/s3-endpoint:/' /etc/proxmox-backup/s3.cfg \
+				 || echo "Failed to rename 's3client' config section-type to 's3-endpoint' in /etc/proxmox-backup/s3.cfg."
+			fi
+		fi
+
 		# TODO: remove with PBS 5+
 		if dpkg --compare-versions "$2" 'lt' '4.0.2~'; then
 			proxmox-backup-manager migrate-config default-notification-mode \
